[
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/141329595",
    "html_url": "https://github.com/expressjs/express/issues/2758#issuecomment-141329595",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/2758",
    "id": 141329595,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MTMyOTU5NQ==",
    "user": {
      "login": "ORESoftware",
      "id": 11139560,
      "node_id": "MDQ6VXNlcjExMTM5NTYw",
      "avatar_url": "https://avatars.githubusercontent.com/u/11139560?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ORESoftware",
      "html_url": "https://github.com/ORESoftware",
      "followers_url": "https://api.github.com/users/ORESoftware/followers",
      "following_url": "https://api.github.com/users/ORESoftware/following{/other_user}",
      "gists_url": "https://api.github.com/users/ORESoftware/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ORESoftware/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ORESoftware/subscriptions",
      "organizations_url": "https://api.github.com/users/ORESoftware/orgs",
      "repos_url": "https://api.github.com/users/ORESoftware/repos",
      "events_url": "https://api.github.com/users/ORESoftware/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ORESoftware/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-18T02:57:43Z",
    "updated_at": "2015-09-18T02:57:43Z",
    "author_association": "NONE",
    "body": "line 47 of our Express app, is of course\n\n```\n// catch 404 and forward to error handler\napp.use(function (req, res, next) {\n    var err = new Error('404: Not Found');   //this line :)\n    err.status = 404;\n    next(err);\n});\n```\n\nso that doesn't help\n",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/141329595/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/141335516",
    "html_url": "https://github.com/expressjs/express/issues/2758#issuecomment-141335516",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/2758",
    "id": 141335516,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MTMzNTUxNg==",
    "user": {
      "login": "dougwilson",
      "id": 67512,
      "node_id": "MDQ6VXNlcjY3NTEy",
      "avatar_url": "https://avatars.githubusercontent.com/u/67512?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dougwilson",
      "html_url": "https://github.com/dougwilson",
      "followers_url": "https://api.github.com/users/dougwilson/followers",
      "following_url": "https://api.github.com/users/dougwilson/following{/other_user}",
      "gists_url": "https://api.github.com/users/dougwilson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dougwilson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dougwilson/subscriptions",
      "organizations_url": "https://api.github.com/users/dougwilson/orgs",
      "repos_url": "https://api.github.com/users/dougwilson/repos",
      "events_url": "https://api.github.com/users/dougwilson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dougwilson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-18T03:45:31Z",
    "updated_at": "2015-09-18T03:45:31Z",
    "author_association": "MEMBER",
    "body": "Basically what is happening is that in your code above, you are creating a new `Error` object on line 47, and then you are calling `next(err)`. If you do not then have any kind of `app.use(function (err, req, res, next) {` declaration after that middleware, the error will be automatically handled by Express, which includes printing the error's stack trace to STDERR.\n",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/141335516/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/141337383",
    "html_url": "https://github.com/expressjs/express/issues/2758#issuecomment-141337383",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/2758",
    "id": 141337383,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MTMzNzM4Mw==",
    "user": {
      "login": "ORESoftware",
      "id": 11139560,
      "node_id": "MDQ6VXNlcjExMTM5NTYw",
      "avatar_url": "https://avatars.githubusercontent.com/u/11139560?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ORESoftware",
      "html_url": "https://github.com/ORESoftware",
      "followers_url": "https://api.github.com/users/ORESoftware/followers",
      "following_url": "https://api.github.com/users/ORESoftware/following{/other_user}",
      "gists_url": "https://api.github.com/users/ORESoftware/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ORESoftware/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ORESoftware/subscriptions",
      "organizations_url": "https://api.github.com/users/ORESoftware/orgs",
      "repos_url": "https://api.github.com/users/ORESoftware/repos",
      "events_url": "https://api.github.com/users/ORESoftware/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ORESoftware/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-18T04:09:06Z",
    "updated_at": "2015-09-18T04:09:06Z",
    "author_association": "NONE",
    "body": "yeah, I guess my question is that I have no idea where the 404 originates from. I am sure it's my error not Express' but it is a mystery. I just changed the above to this:\n\n``` javascript\n// catch 404 and forward to error handler\napp.use(function (req, res, next) {\n    var err = new Error('404: Not Found ' + req.originalUrl); //here\n    err.status = 404;\n    next(err);\n});\n```\n\nwe'll see if I can track it down. The other possiblity is that I am doing this somewhere in the code\n\n``` javascript\nnext(null);\nres.send({});\n```\n\nso what's happening is that the response is being sent successfully, but the 404 error handler is also being invoked, this is probably the case, you can just close this ticket, it's probably my mistake\n",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/141337383/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/141344684",
    "html_url": "https://github.com/expressjs/express/issues/2758#issuecomment-141344684",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/2758",
    "id": 141344684,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MTM0NDY4NA==",
    "user": {
      "login": "dougwilson",
      "id": 67512,
      "node_id": "MDQ6VXNlcjY3NTEy",
      "avatar_url": "https://avatars.githubusercontent.com/u/67512?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dougwilson",
      "html_url": "https://github.com/dougwilson",
      "followers_url": "https://api.github.com/users/dougwilson/followers",
      "following_url": "https://api.github.com/users/dougwilson/following{/other_user}",
      "gists_url": "https://api.github.com/users/dougwilson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dougwilson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dougwilson/subscriptions",
      "organizations_url": "https://api.github.com/users/dougwilson/orgs",
      "repos_url": "https://api.github.com/users/dougwilson/repos",
      "events_url": "https://api.github.com/users/dougwilson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dougwilson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-18T04:58:48Z",
    "updated_at": "2015-09-18T04:58:48Z",
    "author_association": "MEMBER",
    "body": "Ah, I see what you mean; I misunderstood your original request :)\n\nSo, looking at your stack trace there, you can rule out the possibility of those being generated from a `next(null); res.send({})';`, as it shows that a request came in, went through your `bodyParser.json()` and then ended, due to no routes being matched.\n\nYour idea of adding `req.originalUrl` will be your best bet, as based on the stack trace, it's just a request coming into your server that you have no route for. The most common ones would be `/favicon.ico` or `/robots.txt` if you don't have those on your server.\n",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/141344684/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/141349132",
    "html_url": "https://github.com/expressjs/express/issues/2758#issuecomment-141349132",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/2758",
    "id": 141349132,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MTM0OTEzMg==",
    "user": {
      "login": "ORESoftware",
      "id": 11139560,
      "node_id": "MDQ6VXNlcjExMTM5NTYw",
      "avatar_url": "https://avatars.githubusercontent.com/u/11139560?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ORESoftware",
      "html_url": "https://github.com/ORESoftware",
      "followers_url": "https://api.github.com/users/ORESoftware/followers",
      "following_url": "https://api.github.com/users/ORESoftware/following{/other_user}",
      "gists_url": "https://api.github.com/users/ORESoftware/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ORESoftware/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ORESoftware/subscriptions",
      "organizations_url": "https://api.github.com/users/ORESoftware/orgs",
      "repos_url": "https://api.github.com/users/ORESoftware/repos",
      "events_url": "https://api.github.com/users/ORESoftware/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ORESoftware/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-18T05:26:34Z",
    "updated_at": "2015-09-18T05:26:34Z",
    "author_association": "NONE",
    "body": "i see, yeah, that could be it, will let you know, the 404s appeart out of nowhere\n",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/141349132/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/285850505",
    "html_url": "https://github.com/expressjs/express/issues/2758#issuecomment-285850505",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/2758",
    "id": 285850505,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI4NTg1MDUwNQ==",
    "user": {
      "login": "ashenwgt",
      "id": 14919989,
      "node_id": "MDQ6VXNlcjE0OTE5OTg5",
      "avatar_url": "https://avatars.githubusercontent.com/u/14919989?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ashenwgt",
      "html_url": "https://github.com/ashenwgt",
      "followers_url": "https://api.github.com/users/ashenwgt/followers",
      "following_url": "https://api.github.com/users/ashenwgt/following{/other_user}",
      "gists_url": "https://api.github.com/users/ashenwgt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ashenwgt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ashenwgt/subscriptions",
      "organizations_url": "https://api.github.com/users/ashenwgt/orgs",
      "repos_url": "https://api.github.com/users/ashenwgt/repos",
      "events_url": "https://api.github.com/users/ashenwgt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ashenwgt/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-03-11T07:38:44Z",
    "updated_at": "2017-03-11T07:41:43Z",
    "author_association": "NONE",
    "body": "I also got the same error and found this thread while searching an answer. \r\n\r\nHere I'm sharing the way that you should tackle this error.\r\n\r\n1) First comment out the lines which handle your 404 error.\r\n```javascript\r\n// catch 404 and forward to error handler\r\n// app.use(function (req, res, next) {\r\n//    var err = new Error('404: Not Found ' + req.originalUrl); //here\r\n//    err.status = 404;\r\n//    next(err);\r\n// });\r\n```\r\n\r\n2) Now reload your page and you will see something like \r\n\r\n> Cannot GET /(some route)\r\n\r\n3) Understanding: The 404 or Not Found error message is the standard HTTP response code, to indicate that the client was able to communicate with a given server, but the server could not find what was requested. And it now says the missing resource is on the route \"/(some route)\".\r\n\r\n4) Handling the error\r\n\r\nIf it's a web page, the problem is \"/(some route)\" cannot be found in the JS files in ~/routes/ directory. You may have forgotten to handle that route or can be a typo or something. Handle it appropriately.\r\n\r\nIf it's a resource, make sure the resource exists in the mentioned route of your project. \r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/285850505/reactions",
      "total_count": 2,
      "+1": 2,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/445938983",
    "html_url": "https://github.com/expressjs/express/issues/2758#issuecomment-445938983",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/2758",
    "id": 445938983,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ0NTkzODk4Mw==",
    "user": {
      "login": "Dill1",
      "id": 14108378,
      "node_id": "MDQ6VXNlcjE0MTA4Mzc4",
      "avatar_url": "https://avatars.githubusercontent.com/u/14108378?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Dill1",
      "html_url": "https://github.com/Dill1",
      "followers_url": "https://api.github.com/users/Dill1/followers",
      "following_url": "https://api.github.com/users/Dill1/following{/other_user}",
      "gists_url": "https://api.github.com/users/Dill1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Dill1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Dill1/subscriptions",
      "organizations_url": "https://api.github.com/users/Dill1/orgs",
      "repos_url": "https://api.github.com/users/Dill1/repos",
      "events_url": "https://api.github.com/users/Dill1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Dill1/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-12-10T19:22:23Z",
    "updated_at": "2018-12-10T19:22:23Z",
    "author_association": "NONE",
    "body": "For me they were requests to the sourceMapping (.js.map) files for 3rd party js files - I removed the //#sourceMappingURL line in the files. ",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/445938983/reactions",
      "total_count": 3,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 2,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]