[
  {
    "url": "https://api.github.com/repos/cloudinary/cloudinary_npm/issues/comments/560023824",
    "html_url": "https://github.com/cloudinary/cloudinary_npm/issues/320#issuecomment-560023824",
    "issue_url": "https://api.github.com/repos/cloudinary/cloudinary_npm/issues/320",
    "id": 560023824,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MDAyMzgyNA==",
    "user": {
      "login": "aleksandar-cloudinary",
      "id": 48053320,
      "node_id": "MDQ6VXNlcjQ4MDUzMzIw",
      "avatar_url": "https://avatars.githubusercontent.com/u/48053320?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/aleksandar-cloudinary",
      "html_url": "https://github.com/aleksandar-cloudinary",
      "followers_url": "https://api.github.com/users/aleksandar-cloudinary/followers",
      "following_url": "https://api.github.com/users/aleksandar-cloudinary/following{/other_user}",
      "gists_url": "https://api.github.com/users/aleksandar-cloudinary/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/aleksandar-cloudinary/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/aleksandar-cloudinary/subscriptions",
      "organizations_url": "https://api.github.com/users/aleksandar-cloudinary/orgs",
      "repos_url": "https://api.github.com/users/aleksandar-cloudinary/repos",
      "events_url": "https://api.github.com/users/aleksandar-cloudinary/events{/privacy}",
      "received_events_url": "https://api.github.com/users/aleksandar-cloudinary/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-11-30T21:46:27Z",
    "updated_at": "2019-11-30T21:46:27Z",
    "author_association": "CONTRIBUTOR",
    "body": "Hi @PFittech. When using the [delete resources](https://cloudinary.com/documentation/admin_api#delete_resources) method of the Admin API then you can indeed pass an array of public_ids to delete (variant B). Variant A is invalid and won't work for any API calls and that is why Request 1 fails. I can also see the failed [destroy](https://cloudinary.com/documentation/image_upload_api_reference#destroy_method) method calls. Unlike the delete resources method, the destroy only takes a single public_id and your requests were passing an array (variant B) which is why those failed.\r\n\r\nIf you want to use the Admin API then your request should look like this;\r\n\r\n```\r\nvar ids = [ \"labbka/file_e9tfyg\", \"labbka/file_lsb0i5\" ];\r\n\r\ncloudinary.api.delete_resources(\r\n    ids,\r\n    function(error, result) {\r\n        console.log(result, error)\r\n    }\r\n);\r\n```\r\n\r\nAlternatively, passing each ID to the destroy method (resource_type defaults to image so you won't need to pass that unless it's different);\r\n\r\n```\r\ncloudinary.uploader.destroy(\r\n    \"labbka/file_e9tfyg\",\r\n    {\r\n        invalidate: true\r\n    }, \r\n    function(error, result) {\r\n        console.log(result, error)\r\n    }\r\n);\r\n```\r\n\r\nPlease try this out and let me know how it goes.",
    "reactions": {
      "url": "https://api.github.com/repos/cloudinary/cloudinary_npm/issues/comments/560023824/reactions",
      "total_count": 2,
      "+1": 2,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/cloudinary/cloudinary_npm/issues/comments/560063211",
    "html_url": "https://github.com/cloudinary/cloudinary_npm/issues/320#issuecomment-560063211",
    "issue_url": "https://api.github.com/repos/cloudinary/cloudinary_npm/issues/320",
    "id": 560063211,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MDA2MzIxMQ==",
    "user": {
      "login": "ghost",
      "id": 10137,
      "node_id": "MDQ6VXNlcjEwMTM3",
      "avatar_url": "https://avatars.githubusercontent.com/u/10137?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ghost",
      "html_url": "https://github.com/ghost",
      "followers_url": "https://api.github.com/users/ghost/followers",
      "following_url": "https://api.github.com/users/ghost/following{/other_user}",
      "gists_url": "https://api.github.com/users/ghost/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ghost/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
      "organizations_url": "https://api.github.com/users/ghost/orgs",
      "repos_url": "https://api.github.com/users/ghost/repos",
      "events_url": "https://api.github.com/users/ghost/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ghost/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-12-01T06:14:23Z",
    "updated_at": "2019-12-01T06:14:23Z",
    "author_association": "NONE",
    "body": "@aleksandar-cloudinary thank you, You solved my problem. Maybe a quick question why I see **undefined** in response?\r\n\r\n```\r\n {\r\n   deleted: { 'labbka/file_nvjm2i': 'deleted' },\r\n   deleted_counts: { 'labbka/file_nvjm2i': { original: 1, derived: 0 } },\r\n   partial: false,\r\n   rate_limit_allowed: 500,\r\n   rate_limit_reset_at: 2019-12-01T07:00:00.000Z,\r\n   rate_limit_remaining: 497\r\n } undefined\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/cloudinary/cloudinary_npm/issues/comments/560063211/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/cloudinary/cloudinary_npm/issues/comments/560077559",
    "html_url": "https://github.com/cloudinary/cloudinary_npm/issues/320#issuecomment-560077559",
    "issue_url": "https://api.github.com/repos/cloudinary/cloudinary_npm/issues/320",
    "id": 560077559,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MDA3NzU1OQ==",
    "user": {
      "login": "aleksandar-cloudinary",
      "id": 48053320,
      "node_id": "MDQ6VXNlcjQ4MDUzMzIw",
      "avatar_url": "https://avatars.githubusercontent.com/u/48053320?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/aleksandar-cloudinary",
      "html_url": "https://github.com/aleksandar-cloudinary",
      "followers_url": "https://api.github.com/users/aleksandar-cloudinary/followers",
      "following_url": "https://api.github.com/users/aleksandar-cloudinary/following{/other_user}",
      "gists_url": "https://api.github.com/users/aleksandar-cloudinary/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/aleksandar-cloudinary/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/aleksandar-cloudinary/subscriptions",
      "organizations_url": "https://api.github.com/users/aleksandar-cloudinary/orgs",
      "repos_url": "https://api.github.com/users/aleksandar-cloudinary/repos",
      "events_url": "https://api.github.com/users/aleksandar-cloudinary/events{/privacy}",
      "received_events_url": "https://api.github.com/users/aleksandar-cloudinary/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-12-01T08:46:46Z",
    "updated_at": "2019-12-01T08:46:46Z",
    "author_association": "CONTRIBUTOR",
    "body": "@PFittech No problem at all. The undefined in the response corresponds to the 'error' variable that is returned in the callback and is printed at the same time as the 'result'. As the API call didn't produce any errors the 'result' is printed and 'error' is undefined. For example, if you look at your Response 2 in the initial post, you'll notice that the 'result' is undefined and 'error ' has a value. `undefined { message: 'Missing required parameter - public_id', http_code: 400 }`",
    "reactions": {
      "url": "https://api.github.com/repos/cloudinary/cloudinary_npm/issues/comments/560077559/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/cloudinary/cloudinary_npm/issues/comments/1146022545",
    "html_url": "https://github.com/cloudinary/cloudinary_npm/issues/320#issuecomment-1146022545",
    "issue_url": "https://api.github.com/repos/cloudinary/cloudinary_npm/issues/320",
    "id": 1146022545,
    "node_id": "IC_kwDOAEh2wM5ETuqR",
    "user": {
      "login": "promiselxg",
      "id": 14315839,
      "node_id": "MDQ6VXNlcjE0MzE1ODM5",
      "avatar_url": "https://avatars.githubusercontent.com/u/14315839?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/promiselxg",
      "html_url": "https://github.com/promiselxg",
      "followers_url": "https://api.github.com/users/promiselxg/followers",
      "following_url": "https://api.github.com/users/promiselxg/following{/other_user}",
      "gists_url": "https://api.github.com/users/promiselxg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/promiselxg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/promiselxg/subscriptions",
      "organizations_url": "https://api.github.com/users/promiselxg/orgs",
      "repos_url": "https://api.github.com/users/promiselxg/repos",
      "events_url": "https://api.github.com/users/promiselxg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/promiselxg/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-06-03T14:29:12Z",
    "updated_at": "2022-06-03T14:29:12Z",
    "author_association": "NONE",
    "body": "@aleksandar-cloudinary thanks.",
    "reactions": {
      "url": "https://api.github.com/repos/cloudinary/cloudinary_npm/issues/comments/1146022545/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]