[
  {
    "url": "https://api.github.com/repos/lodash/lodash/issues/comments/313003604",
    "html_url": "https://github.com/lodash/lodash/issues/3245#issuecomment-313003604",
    "issue_url": "https://api.github.com/repos/lodash/lodash/issues/3245",
    "id": 313003604,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMxMzAwMzYwNA==",
    "user": {
      "login": "chzhm159",
      "id": 5073707,
      "node_id": "MDQ6VXNlcjUwNzM3MDc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5073707?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chzhm159",
      "html_url": "https://github.com/chzhm159",
      "followers_url": "https://api.github.com/users/chzhm159/followers",
      "following_url": "https://api.github.com/users/chzhm159/following{/other_user}",
      "gists_url": "https://api.github.com/users/chzhm159/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chzhm159/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chzhm159/subscriptions",
      "organizations_url": "https://api.github.com/users/chzhm159/orgs",
      "repos_url": "https://api.github.com/users/chzhm159/repos",
      "events_url": "https://api.github.com/users/chzhm159/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chzhm159/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-07-05T06:01:09Z",
    "updated_at": "2017-07-05T06:01:09Z",
    "author_association": "NONE",
    "body": "My mistake,i  used  v2.4.1. update to v4.1.7.4 error was gone.",
    "reactions": {
      "url": "https://api.github.com/repos/lodash/lodash/issues/comments/313003604/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/lodash/lodash/issues/comments/450078750",
    "html_url": "https://github.com/lodash/lodash/issues/3245#issuecomment-450078750",
    "issue_url": "https://api.github.com/repos/lodash/lodash/issues/3245",
    "id": 450078750,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ1MDA3ODc1MA==",
    "user": {
      "login": "lock[bot]",
      "id": 33595554,
      "node_id": "MDM6Qm90MzM1OTU1NTQ=",
      "avatar_url": "https://avatars.githubusercontent.com/in/6672?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lock%5Bbot%5D",
      "html_url": "https://github.com/apps/lock",
      "followers_url": "https://api.github.com/users/lock%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/lock%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/lock%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lock%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lock%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/lock%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/lock%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/lock%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lock%5Bbot%5D/received_events",
      "type": "Bot",
      "site_admin": false
    },
    "created_at": "2018-12-27T05:38:01Z",
    "updated_at": "2018-12-27T05:38:01Z",
    "author_association": "NONE",
    "body": "This thread has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.\n",
    "reactions": {
      "url": "https://api.github.com/repos/lodash/lodash/issues/comments/450078750/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]